baseurl = "https://thassan.netlify.app/"
languageCode = "en-US"
title = "Taimur Hassan"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "image0.jpeg"
  author = "Taimur Hassan"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "taimurh"
  LinkedIn      = "www.linkedin.com/in/taimur-hassan-632447184"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "Project 1"
  identifier = "project 1"
  weight = 200
  url = "/project1/"
[[menu.main]]
  name = "Project 2"
  identifier = "project 2"
  weight = 200
  url = "/project2/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/Resume/"
