---
title: The Cost of Heroism Through the Lens of the Trojan War
author: ''
date: '2020-07-22'
slug: the-cost-of-heroism-through-the-lens-of-the-trojan-war
categories: []
tags: []
description: ''
---
What is The Cost of Heroism?

While modern interpretations render heroism distinctly in the category of the brave bordering to magnanimity, a strictly classical sense defines a hero as someone associated with the idea of glory (kleos). The epic poem Iliad by Homer describes heroism in a classical way, where heroism can lead to both brilliant feats and unflinching injustice. Iliad is a description of the Trojan War, and a prerequisite of winning a war is displaying fearless heroism. Nonetheless, some would argue that heroism in the Iliad doesn’t have benefits that could outweigh costs. While it is indisputably true that the actions of some heroes, such as Achilles, in the Iliad do not signify good heroism and perhaps even border insanity, it should be kept in mind that in the social context of the Iliad, where there were laws and rules unfamiliar and not intricate as contemporary times, heroism takes on a different narrative and its power to unite and inspire might slightly undermine its capacity to injure and carry acts of injustice.

Heroes in the Iliad are depicted as supernatural entities. They are somewhat divine and are usually demi-gods who live the life of mortals. Apart from being associated with glory, especially on the battlefield, they have a power and an aura not found within mortals. Achilles, for example, is considered a fast runner and this is often reiterated occasionally in the entire Iliad as an epithet. For example, Achilles is referred to as being “as fast as a lion,” in the very beginning of the Iliad (Homer, Iliad Book 1, 13). While everyone battles on the battlefield in a relatively mundane manner, when the hero battles, everything seems to come to a standstill as everyone wants to peek at the astonishing power hidden inside one man. Other examples of heroes in the Iliad are Sarpedon, who is the son of Zeus, Ajax and Odysseus. 
The Iliad brings the idea of kleos (glory), time (honor) and geras (prize, reward) while discussing the beginning of the Trojan War and the heroes within. As Agamemnon refuses to ransom the daughter of Khyrses, a priest of Apollo, Apollo plagues the Greeks. Agamemnon agrees to give up his prize, but insists on taking Achilles’ prize, Briseis. This loss of Agamemnon’s geras (reward, prize) insinuates a loss in time, and the only way it can be compensated is by receiving geras of similar value. Achilles argues, rightfully so, that Agamemnon fights less and gets more than he deserves, including prizes (geras). The idea that Achilles stands against Agamemnon for how he operates signifies the importance of kleos, which is only achieved on the battlefield. This is a great aspect of heroism displayed by Achilles as he asks for the right thing, indifferent to what Agamemnon says. Achilles portrays more kleos and receives less gifts – this is unbearably wrong, as he and his fellow men shed blood, while Agamemnon does not fight in comparison to them. Later, Achilles refuses to fight for the Greeks and asks Thetis, his mother, to ask for aid from Zeus against the Greeks. With the whole melting pot of ideas of kleos, time and geras, and the notion that Achilles’ mother is a goddess reinforces the supernatural idea of a hero, distinct from mortal heroes.

The Iliad also focuses on describing moments of rampage by different heroes. Diomedes goes on a rampage and kills many Trojans. Later, Patroclus has his own rampage as he wears Achilles’ armor to rouse Greek moral. This is a very significant event as Greeks, thinking that it is Achilles, attack the Trojans more fiercely in unison. The idea that the return of a person, albeit someone as powerful and supernatural as Achilles, inculcating inspiration in the hearts of the Greek soldiers implies the advantages of having a hero. Even when Patroclus dies, while in the armor of Achilles, he utters, “I’ll tell you one more thing; take it to heart. No long life is ahead for you. This day your death stands near, and your immutable end, at Prince Akhilleus’ hands” (Homer, Iliad Book 16, 403). The aforementioned quote accentuates the importance of heroism, and having a hero as powerful as Achilles on one’s side, as that would foster not only strength in one’s own army but also fear in the hearts of one’s opponents.
The culture associated with the aforementioned characteristics of a hero is that of highly patriarchal, ancient Greece. It promotes the idea of masculinity above everything, and women are in complete subjugation to the will of men. The Trojan War (canonical date: 1194-1184 BCE) itself is a result of a woman fleeing to find love with another man. Another aspect of the culture is the notion of glory or kleos in the battlefield. No man can achieve glory in any other way except by performing well in a battle. The Greek political system is that of a monarchy, controlled by Agamemnon, with little to no say by the populace, except a handful of advisors. It is important to mention that Homer is writing the Iliad during the rise of the polis and is discussing the late Greek Bronze Age in terms of Agamemnon and the Palace of Mycenae. Thus, the values or beliefs held by Greeks in the Iliad, especially regarding heroism, are bound to be very different than the people of the modern world.

While it is important to highlight the benefits of heroism in the particular case of the Iliad, there are certain disadvantages which are noteworthy to mention. After the death of Patroclus, Achilles has a persistent fit of anger, where he refuses nourishment. This refusal of food and godly anger hints towards the ancient model of heroism, where the hero channels his strength through a divine source. Perhaps the most gruesome scene in the Iliad occurs when Achilles kills Hektor and binds Hektor to his chariot. His mutilation of Hektor’s body complicates the understanding of heroism as it is an act that would hardly be expected from a hero who everybody looks upon. While it is understandable that Achilles feels great pain and grief at the death of Patroclus, it does not give him permission to mutilate Hektor’s body and prevent Hektor’s family to giving him proper funeral rites. When Priam comes to Achilles to request Hektor’s body, Achilles says, “Therefore, let me be. Sting my sore heart again, and even here, under my own roof, suppliant though you are, I may not spare you, sir, but trample on the express command of Zeus” (Homer, Iliad Book 24, 586). This suggests that Achilles is so hurt by the death of Patroclus that he would even dare to kill Priam, King of the Trojans. While it is understandable to a certain degree that grief can bring feelings of revenge and cloud one’s judgement, Achilles seems to have been overwhelmed by grief, anger and wrath. The uncontrolled fury Achilles feels brings doubts to readers about the nature of heroism and whether the toll it brings of injustice and injury is worth the set of benefits. Yet, it should be kept in mind that Achilles, nonetheless, was perhaps the most important man in the Greek camp as he turned the wave of the Trojan War by killing their formidable fighter, Hektor. 

In a nutshell, heroism can have several benefits but can come with costs that seem troubling. As in the case of the Iliad, heroism proved to be effective, especially for fighters such as Diomedes, Odysseus, Ajax, and Achilles. Achilles might have altered the balance of benefits and costs in the model of heroism more than his counterparts but his effectiveness as a fighter and his role in the Trojan War leads to the consideration that benefits of heroes, especially those like Achilles with divine power, will outweigh the costs. The divine energy inside heroes will help kings win wars. Achilles was easily the best man Agamemnon could ask for, and it is a question left for classical mythologists to interpret what would the Greeks have done without Achilles and his ability to inspire his fellow soldiers.
