---
title: "Resume"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
EDUCATION

•	2013	Completed University of Cambridge, GCE Ordinary Levels, with 7 A*’s and 3 A’s (High School)

•	2015	Completed University of Cambridge, GCE Advanced Levels, with 4 A*’s and 1 B (High School)

•	2017-	Enrolled in the University of Texas at Austin, Austin, TX – Bachelor of Science in Biology (Pre-Med)				Anticipated Graduation Date: Spring 2020		Concentration in Biology; Cumulative GPA = 3.85 (as of current)

•	2019	MCAT score of 509	

EXTRACURRICULAR AND VOLUNTEER HISTORY (STARTING COLLEGE)

•	Volunteered at a Robotics Camp at San Jacinto College in November, 2016 - responsible for maintaining robots, learning JavaScript and introduction to coding (including R and Python), confirming that every robot was taken care of properly, ensuring proper robot working order

•	Volunteer at Shaukat Khanum Hospital in Pakistan in 2016 for a total of 160 hours.

•	Responsible for taking care of children affected by cancer; empowering them and their parents with hope and belief; playing board games with children and teaching them basic skills such as coloring; promoted to supervisor of a group of volunteers; ensuring that all volunteers follow protocol.

•	Administrator of online affairs of the Planetary Society. I was responsible for maintaining all social accounts of the Pakistan Chapter of the Society. It took me 6 hours per week, and 50 weeks per year for a total of 3 years. Organized a Star Show for an Orphanage called SOS at the National Planetarium in Lahore.

•	Attended Success in Science, a lecture by leading Neuroscientists, Dr. Michael Mauk and Dr. Michael Drew, on their amazing journey in their scientific fields

•	Fundraising at Local Mosque in Austin during a period of 6 months

•	Internship at Ghani Welfare Foundation, taking me 10 hours per week for three months. Here I taught English, Mathematics, and Science to underprivileged children, mostly orphans, at the Primary Education Department

•	Shadowed Dr. Night Mirza, a psychiatrist in New Jersey, for 120 hours

•	Shadowed Dr. Mohamed M Haq, an oncologist in Houston, for 120 hours

•	Shadowed Dr. Omar Akhtar, an orthopedic surgeon in Austin, for 30 hours

•	Shadowed Dr. Mohammad Tariq, an anesthesiologist in Dallas, for more than 300 hours (continuing)
•	Apart from shadowing at his clinic, also had in-depth conversations about healthcare in America, underrepresentation, and career trajectory

•	Participated in a high energy Neutrino Physics Research lab, for 265 hours 
•	Part of the undergraduate team for optic fiber cutting
•	Helped in finalizing the optic fiber cutting plan to optimize performance for all students involved
•	Worked on cutting and labelling by following proper safety protocol
•	Presented presentations on team performance and weekly outcomes
•	Attended weekly meetings to assess performance enhancing techniques
•	Involved in liquid scintillation counting research with Professor Junting Huang

•	Medical Scribing
•	Virtual and On-site Medical Scribe for Robin Healthcare, a company that uses Artificial Intelligence conjoined with medicine – primarily responsible for documenting doctors notes and assisting in compilation (during Spring 2020 and onwards; commitment for a full year and a half)

•	Involved in Peer-Led Undergraduate Studying (PLUS) as a leader (PLUS facilitator) of a cohort of students of Upper Division Marine Ecology
•	Leading study groups for a full semester 
•	Helping other students decipher complex issues related to marine science
•	Providing useful tips and strategies on how to approach studying

•	Volunteer Notetaker for Spring Semester 2020 for Marine Ecology for a Student with a Disability
•	Taking notes and writing any important announcements for each class
•	Sharing notes with students with a variety of disabilities including, but not limited to, ADHD, Learning Disabilities, Visual Disabilities, Deaf/Hard of Hearing, Psychological Disabilities, Traumatic Brain Injury, Autism and Medical Disabilities.
•	A total of 60 hours across 15 weeks

•	Teaching Biology, Physics, Chemistry and Mathematics to middle and high school students from 2018-2020 (up till now) every week for 5 hours; also helping them with SAT and appropriate college preparation

PLANNED ACTIVITIES

•	Going to participate in Neuroinflammation/Spinal Cord Injury Research during Summer 2020 with Dr. Andrew Gaudet (from May 2020 to May 2021)


AWARDS AND HONORS

•	Awarded Outstanding Achievement Award in Academics in High School

•	Dean’s Honor List from 2016-2017 and 2019.

JOBS

•	Tutoring 9th graders Biology, Physics and Chemistry for 3 years in a Tutoring Academy

•	Worked at Kumon for 6 months – a teaching center designed to empower students with basic knowledge in the sciences from a young age

•	Cashier at Jack’s Grocery for 11 months – performed day-to-day dealings with customers and prioritized customer satisfaction

•	Cashier at Mosaic Mart

INTERESTS AND HOBBIES

•	Programming and fluent in JavaScript, R, and Python

•	Understanding the deep complexities in the Human Body

•	Learning focused on the Human Brain and Mind

•	Avid Soccer player

•	Listening to Music

•	Artificial Intelligence

•	Space Exploration

